
/* Operadores Lógicos, entendendo a tabela verdade */

/* Mudar para o projeto */

use projeto;

/* Mostrando as tabelas */

show tables; 

/* OR */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

/* AND */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* COUNT (*), GROUP BY, PERFORMANCE COM OPERADORES LOGICO */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS "Quantidade de registro da tab. Cliente" FROM CLIENTE;


/* OPERADOR GROUP BY */


SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

/* PERFORMANCE EM OPERADORES LOGICOS */

/*

PARA CONTAR 
SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE GROUP BY CIDADE;

CONDICAO = F 
CIDADE = RIO DE JANEIRO 

SITUACAO - TRATANDO COM OU / OR 
70% MULHERES = SEXC = F 
30% MORA NO RIO DE JANEIRO 

COLOCA O STATEMENT DE SEXO = 'F' PRIMEIRO, POIS A UMA DE CHANCE DE 70% DELE SER VERDADE, 
SE FOR O BANCO N?O PRECISARA CHECAR O SEGUNDO STATEMENT QUE HA APENAS 30% DE CHANCE DE SER VERDADE. 
PODEMOS FAZER ASSIM, CASO ESTEJAMOS UTILIZANDO O 'OR' 

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR CIDADE = 'RIO DE JANEIRO';

SITUACAO - TRATANDO COM E / AND  
70% MULHERES = SEXC = F 
30% MORA NO RIO DE JANEIRO 

COLOCA O STATEMANET DE CIDADE PRIMEIRO, POIS HA UMA CHANCE 70% DE SER FALSO (OU 30% DE CHANCE DE VERDADEIRO), 
ASSIM O BANCO N?O PRECISA CHEGAR O SEGUNDO CASO ELE SEJA FALSO, AQUI ESTAMOS USANDO O 'AND'

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE CIDADE = 'RIO DE JANEIRO' AND SEXO = 'F';


 */

