
/* SELEÇÃO, PROJEÇÃO E JUNÇÃO*/


/* PROJEÇÃO => TUDO QUE VC QUER VER NA TELA */

SELECT * FROM CLIENTE;

SELECT NOW();

SELECT 2 + 2 AS SOMA, NOME, NOW() FROM CLIENTE;

/* SELEÇÃO => É UM SUBCONJUNTO DE UM CONJUNTO TOTAL DE REGISTROS DE UMA TABELA,
A CLAUSULA DA SELEÇÃO É O WHERE*/

SELECT NOME, EMAIL /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; /* SELEÇÃO */

SELECT BAIRRO FROM ENDERECO WHERE ID_CLIENTE = 1; 

SELECT NUMERO FROM TELEFONE WHERE TIPO = 'CEL';

/* JUNÇÃO -> JOIN */

SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE FROM ENDERECO;

/* FUNCIONA, MAS NAO É O IDEAL PARA USO */
SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJECAO */
FROM CLIENTE, ENDERECO /* ORIGEM */
WHERE IDCLIENTE = ID_CLIENTE; /* JUNCAO */


SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE AND SEXO = 'F';

/*POIS ISSO AQUI IDCLIENTE = ID_CLIENTE SEMPRE SERA VERDADE,
POR CONTA DA MODELAGEM DAS TABELAS, USANDO O 
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE) 
ISSO FAZ QUE PARA VOCE INSERIR UM ENDEREÇO, PRECISA EXISTIR UM CLIENTE COM AQUELE ID
*/
