/* Mudar para o projeto */

use projeto;

/* Mostrando as tabelas */

show tables; 

/* exibindo a estrutura de uma tabela */

desc cliente; 

/* SINTAXE BASICA PARA INSERCAO => INSERT INTO TABELA_NOME ... */

/* forma 01 - omitindo as colunas | tem que estar na ordem que foi definido na tabela*/

INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 54152156, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO');

INSERT INTO CLIENTE VALUES('JORGE', 'M', NULL, 885755895, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('lINEAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '548556885', 85548962);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL*/

INSERT INTO CLIENTE VALUE('ANA', 'F', 'ANA@GMAIL.COM', 885755835, '58728895', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'), 
('CARLA', 'F', 'CARLA@TERATT.COM.BR', 775755895, '66748895', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/* Esse dar erro, pois o valor que esta em cpf esta fora do limite dentro de inteiro no mysql */
INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('CLARA', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '12345678', 12345678912);

/* selecao projecao e juncao */
/* COMANDO SELECT - para projecao */

SELECT NOW();

SELECT NOW() as DATA_HORA;

SELECT NOW() as DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* show tables É UM PONTEIRAMENTO PARA UM SELECT */